spring.application.name=SpringSecurity

#changing the default username and password
spring.security.user.name=satyam
spring.security.user.password=1234

#stop 3rd party from requestion
spring.servlet.session.cookie.same=strict