spring.application.name=SpringSecurity

#changing the default username and password
spring.security.user.name=satyam
spring.security.user.password=1234

#stop 3rd party from requestion
spring.servlet.session.cookie.same=strict


spring.datasource.url=jdbc:postgresql://localhost:5432/SpringSecurity
spring.datasource.username=postgres
spring.datasource.password=satyam721
spring.datasource.driver-class-name=org.postgresql.Driver


#creates table if doesnt exist
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

